# Generated by Django 2.0.2 on 2020-04-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldsrelatedonetoonefield', max_length=100),
        ),
    ]
