# Generated by Django 2.0.2 on 2020-10-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20201011_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Cloud', max_length=250),
        ),
    ]
