# Generated by Django 2.0.2 on 2020-04-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOI', '0004_auto_20200427_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='thumbnail',
            field=models.ImageField(upload_to='aoi_pics'),
        ),
    ]
