# Generated by Django 2.0.2 on 2020-04-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOI', '0007_auto_20200427_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='vids'),
        ),
    ]
