# Generated by Django 2.0.2 on 2020-10-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOI', '0009_auto_20201011_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='chi_gained',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='vids'),
        ),
    ]
