# Generated by Django 2.0.2 on 2020-10-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AOI', '0011_auto_20201011_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vids'),
        ),
    ]
