# Generated by Django 2.0.2 on 2020-10-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=False, related_name='receiver', to='Profile.Profile'),
        ),
    ]
